## Aula 03
Introdução a aula 03
---
- Biblioteca Pandas
- Biblioteca Numpy
---
```python
print("Olá mundo")
```

1. Conhecendo a bibliotecas
2. Executando comandos

In [1]:
import pandas as pd
import numpy as np

In [2]:
quantidades_produtos = [3,5,6,10]
precos_produtos = [10,5,7,100]
nomes_produtos = ["Pastel", "Caçulinha", "Refrigerante", "Combos"]

array_produtos = np.array(quantidades_produtos)
array_precos = np.array(precos_produtos)

faturamento = array_produtos * array_precos
for nome,preco in zip(nomes_produtos,faturamento):
    print(f"{nome} : {preco}")

Pastel : 30
Caçulinha : 25
Refrigerante : 42
Combos : 1000



### Exercicios de fixação 
- Criar uma lista que ira possuir 10 nomes de produtos
- Criar uma lista que ira possuir o preço de custo (atacado)
- Criar uma lista que ira possuir o preço de venda (varejo)
- Ao final, exibir o lucro obtido em cada produto

In [3]:
import numpy as n
import pandas as p

nome_produto = ["maça", "banana", "pera", "uva", "whey", "creatina", "pre-treino", "trembolona", "ovo", "manga"]
preco_atc = [1.50, 1, 2, 0.50, 60, 80, 40, 300, 2, 0.75]
preco_vj = [0.50, 1, 2, 0.50, 50, 70, 30, 250, 1, 0.50]

array_atc = n.array(preco_atc)
array_vj = n.array(preco_vj)

lucro = array_atc - array_vj
for nomes,precos in zip(nome_produto,lucro):
    print(f"{nomes}: {precos}")

print(n.sum(lucro))

maça: 1.0
banana: 0.0
pera: 0.0
uva: 0.0
whey: 10.0
creatina: 10.0
pre-treino: 10.0
trembolona: 50.0
ovo: 1.0
manga: 0.25
82.25

# Pandas

In [4]:
df = pd.read_csv(r".\data\dataset_aula1_numpy_pandas.csv")
df.head() # Por padrão, ele exibe as 5 primeiras informações

   id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0            1  Montagem          72.62          41.77           111      0
1            2  Usinagem          81.65          34.08           128      0
2            3  Usinagem          68.87          39.44           159      0
3            4  Usinagem          66.84          34.52            98      0
4            5  Usinagem          66.23          31.57            94      0

In [5]:
df.tail() # Exibe as 5 ultimas

    id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
35           36  Usinagem          68.47          36.87            87      0
36           37  Inspeção          75.62          30.78           125      1
37           38  Usinagem          78.50          36.39            90      0
38           39  Montagem          76.19          36.54           111      1
39           40  Montagem          68.64          34.88           102      0

In [6]:
df.shape # Dimesões da tabela

(40, 6)

In [7]:
df.columns

Index(['id_registro', 'setor', 'temperatura_c', 'tempo_ciclo_s',
       'producao_dia', 'falha'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_registro    40 non-null     int64
 1   setor          40 non-null     str
 2   temperatura_c  40 non-null     float64
 3   tempo_ciclo_s  40 non-null     float64
 4   producao_dia   40 non-null     int64
 5   falha          40 non-null     int64
dtypes: float64(2), int64(3), str(1)
memory usage: 2.3 KB

In [9]:
# Contar valores duplicados
df.duplicated().sum()

np.int64(0)

In [10]:
# Contar valores nulos
df.isna().sum()

id_registro      0
setor            0
temperatura_c    0
tempo_ciclo_s    0
producao_dia     0
falha            0
dtype: int64

In [11]:
df.describe()

       id_registro  temperatura_c  tempo_ciclo_s  producao_dia      falha
count    40.000000      40.000000      40.000000     40.000000  40.000000
mean     20.500000      72.525750      35.103250    116.400000   0.300000
std      11.690452       5.923691       3.918479     26.071696   0.464095
min       1.000000      60.310000      27.200000     80.000000   0.000000
25%      10.750000      68.597500      32.580000     92.750000   0.000000
50%      20.500000      73.425000      34.960000    111.000000   0.000000
75%      30.250000      76.310000      36.925000    136.750000   1.000000
max      40.000000      85.020000      47.450000    159.000000   1.000000

# Subir a base de dados
- Mostrar os 5 primeiros
- Mostrar os 5 ultimos 
- Mostrar a descrição

In [12]:
df = pd.read_csv(r".\data\dataset_techshop_vendas.csv")
df.head()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
0,2024-01-01,Acessórios,36.20,1,Sudeste,Instagram,3.3
1,2024-01-01,Acessórios,122.61,5,Sudeste,Orgânico,4.4
2,2024-01-02,Acessórios,151.19,4,Sul,Google Ads,4.6
3,2024-01-03,TVs,3399.16,2,Sudeste,Google Ads,4.1
4,2024-01-04,Smartphones,3180.94,2,Nordeste,Instagram,3.9

In [13]:
df.tail()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
795,2024-12-27,Áudio,1128.44,4,Sul,Orgânico,4.6
796,2024-12-27,Acessórios,209.29,4,Sudeste,Google Ads,3.8
797,2024-12-28,Notebooks,7979.84,2,Sudeste,Google Ads,4.4
798,2024-12-28,Notebooks,4168.01,1,Nordeste,Instagram,4.1
799,2024-12-28,Acessórios,111.95,1,Sul,Google Ads,4.7

In [14]:
df.describe()

       preco_unitario  quantidade   avaliacao
count      800.000000  800.000000  800.000000
mean      2173.764038    2.237500    4.165500
std       2042.173946    1.306034    0.542658
min         20.070000    1.000000    2.400000
25%        249.837500    1.000000    3.800000
50%       1458.565000    2.000000    4.200000
75%       3707.427500    3.000000    4.600000
max       7979.840000    5.000000    5.000000