In [55]:
# Importação de bibliotecas
import numpy as np # np sera o apelido

In [56]:
temperaturas = np.array([30, 40, 50, 60, 70, 80, 90, 100])
print(temperaturas)
print(type(temperaturas))

[ 30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>

In [57]:
# Media aritmetica
media = np.mean(temperaturas)
print(f"{media:.2f}")

65.00

In [58]:
# Maior valor
maior_valor = np.max(temperaturas)
print(maior_valor)

100

In [59]:
# Menor valor
menor_valor = np.min(temperaturas)
print(menor_valor)

30

In [60]:
salarios = np.array([2,3,4,5,1,500])
media_salarios = np.mean(salarios)
print(f"{media_salarios:.2f}")

85.83

In [61]:
mediana = np.median(salarios)
print(salarios)

[  2   3   4   5   1 500]

Desafio final
- criar um array de habitantes de 5 cidades do estado de SP
- maior população 
- menor população
- mediana

In [62]:
import numpy as sp

In [63]:
cidades = sp.array([11451999, 1291771, 1139047,810729, 748919])

print(cidades)

maior_pop = sp.max(cidades)
print(f"A maior é: {maior_pop}")

menor_pop = sp.min(cidades)
print(f"A menor é: {menor_pop}")

mediana_pop = sp.median(cidades)
print(f"A mediana é: {mediana_pop}")

media_pop = sp.mean(cidades)
print(f"A media é: {media_pop}")

[11451999  1291771  1139047   810729   748919]
A maior é: 11451999
A menor é: 748919
A mediana é: 1139047.0
A media é: 3088493.0

In [64]:
import pandas as pd
df = pd.read_csv(r".\data\dataset_aula1_numpy_pandas.csv")
df.head()

   id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0            1  Montagem          72.62          41.77           111      0
1            2  Usinagem          81.65          34.08           128      0
2            3  Usinagem          68.87          39.44           159      0
3            4  Usinagem          66.84          34.52            98      0
4            5  Usinagem          66.23          31.57            94      0

In [65]:
df[["temperatura_c","falha"]]

    temperatura_c  falha
0           72.62      0
1           81.65      0
2           68.87      0
3           66.84      0
4           66.23      0
5           64.79      0
6           85.02      1
7           60.31      0
8           75.84      0
9           68.38      1
10          76.31      0
11          74.79      0
12          76.31      0
13          63.28      0
14          64.98      0
15          81.48      0
16          79.62      1
17          69.80      0
18          77.16      0
19          73.30      1
20          79.77      0
21          71.76      0
22          74.16      0
23          74.69      1
24          74.03      1
25          75.96      0
26          60.80      0
27          69.37      1
28          70.28      0
29          73.53      0
30          63.59      1
31          68.91      0
32          77.62      1
33          73.32      1
34          78.24      0
35          68.47      0
36          75.62      1
37          78.50      0
38          76.19      1
39          68.64      0

In [68]:
df["classificacao_temperatura"] = np.where(df["temperatura_c"]>=75,"temperatura alta","temperatira baixa")
df.head()

,id_registro,setor,temperatura_c,tempo_ciclo_s,producao_dia,falha,classificacao_temperatura
0,1,Montagem,72.62,41.77,111,0,temperatira baixa
1,2,Usinagem,81.65,34.08,128,0,temperatura alta
2,3,Usinagem,68.87,39.44,159,0,temperatira baixa
3,4,Usinagem,66.84,34.52,98,0,temperatira baixa
4,5,Usinagem,66.23,31.57,94,0,temperatira baixa